# Generated by Django 5.1.6 on 2025-04-18 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosya',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dosya_no', models.IntegerField(unique=True)),
                ('kayit_tarihi', models.DateField()),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('kimlik_no', models.CharField(max_length=20)),
                ('profil_resmi', models.ImageField(blank=True, null=True, upload_to='profil_resimleri/%Y/%m/')),
                ('uyruk', models.CharField(choices=[('TC', 'Türkiye'), ('SURIYE', 'Suriye'), ('IRAK', 'Irak'), ('IRAN', 'İran'), ('AFGANISTAN', 'Afganistan'), ('SUDAN', 'Sudan'), ('DIGER', 'Diğer')], default='TC', max_length=20)),
                ('telefon', models.CharField(max_length=20)),
                ('ilce', models.CharField(default='Yeni Mahalle', max_length=100)),
                ('mahalle', models.CharField(max_length=100)),
                ('cadde_sokak', models.CharField(max_length=100)),
                ('bina_no', models.CharField(max_length=20)),
                ('daire_no', models.CharField(max_length=20)),
                ('kira_durumu', models.CharField(choices=[('KIRACI', 'Kiracı'), ('EV_SAHIBI', 'Ev Sahibi')], max_length=20)),
                ('gelir_durumu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dolduran_kisi', models.CharField(max_length=100)),
                ('iban', models.CharField(blank=True, max_length=50, null=True)),
                ('yardim_aldigi_yerler', models.TextField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], default='BEKLEMEDE', max_length=20)),
                ('notlar', models.TextField(blank=True, null=True)),
                ('guncellenme_tarihi', models.DateTimeField(auto_now=True)),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dosyalar',
                'ordering': ['-kayit_tarihi'],
                'default_related_name': 'dosyalar',
            },
        ),
        migrations.CreateModel(
            name='AileBilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('kimlik_no', models.CharField(blank=True, max_length=20, null=True)),
                ('yakinlik', models.CharField(choices=[('KENDISI', 'Kendisi'), ('ES', 'Eş'), ('COCUK', 'Çocuk'), ('ANNE', 'Anne'), ('BABA', 'Baba'), ('KARDES', 'Kardeş'), ('DIGER', 'Diğer')], default='DIGER', max_length=20)),
                ('cinsiyet', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], default='E', max_length=1)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('engel_durumu', models.BooleanField(default=False)),
                ('engel_aciklama', models.TextField(blank=True, null=True)),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aile_bilgileri', to='dosyalar.dosya')),
            ],
            options={
                'db_table': 'aile_bilgileri',
            },
        ),
        migrations.CreateModel(
            name='DurumDegisikligi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eski_durum', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], max_length=20)),
                ('yeni_durum', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('ONAYLANDI', 'Onaylandı'), ('REDDEDILDI', 'Reddedildi')], max_length=20)),
                ('degisiklik_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('degistiren', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durum_degisiklikleri', to='dosyalar.dosya')),
            ],
            options={
                'db_table': 'durum_degisiklikleri',
                'ordering': ['-degisiklik_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Belge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belge_turu', models.CharField(choices=[('KONTRAT', 'Kontrat'), ('OLUM_BELGESI', 'Ölüm Belgesi'), ('VUKUATLI_NUFUS', 'Vukuatlı Nüfus Kayıt Örneği'), ('OGRENCI_BELGESI', 'Öğrenci Belgesi'), ('BANKA_EKSTRESI', 'Banka Ekstresi'), ('TEMVIYYE', 'Temviyye')], max_length=50)),
                ('belge', models.FileField(upload_to='belgeler/%Y/%m/')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belgeler', to='dosyalar.dosya')),
            ],
            options={
                'db_table': 'belgeler',
                'unique_together': {('dosya', 'belge_turu')},
            },
        ),
    ]
