# Generated by Django 5.1.6 on 2025-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosya',
            name='engel_durumu',
            field=models.BooleanField(default=False),
        ),
    ]
