# Generated by Django 5.2 on 2025-04-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0002_dosya_engel_durumu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosya',
            name='engel_durumu',
        ),
        migrations.AlterField(
            model_name='ailebilgisi',
            name='engel_durumu',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
