# Generated by Django 5.2 on 2025-05-02 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0003_remove_dosya_engel_durumu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaddiYardim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maddi_yardimlar', to='dosyalar.dosya')),
            ],
            options={
                'verbose_name': 'Maddi Yardım',
                'verbose_name_plural': 'Maddi Yardımlar',
            },
        ),
    ]
