# Generated by Django 5.2 on 2025-05-02 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0004_maddiyardim'),
    ]

    operations = [
    ]
