# Generated by Django 5.2 on 2025-05-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0005_auto_20250502_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maddiyardim',
            name='dosya',
        ),
        migrations.AddField(
            model_name='maddiyardim',
            name='dosyalar',
            field=models.ManyToManyField(related_name='maddi_yardimlar', to='dosyalar.dosya'),
        ),
        migrations.AddField(
            model_name='maddiyardim',
            name='yardim_yapan_ad_soyad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='maddiyardim',
            name='yardim_yapan_telefon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
