# Generated by Django 5.2 on 2025-05-05 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0007_dosyatutari'),
    ]

    operations = [
        migrations.CreateModel(
            name='SahsiYardim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yardim_tipi', models.CharField(choices=[('individual', 'Bireysel'), ('group', 'Grup')], max_length=20)),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('grup_uye_sayisi', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosyalar', models.ManyToManyField(related_name='sahsi_yardimlar', to='dosyalar.dosya')),
            ],
        ),
        migrations.CreateModel(
            name='SahsiYardimci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('yardim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yardimcilar', to='dosyalar.sahsiyardim')),
            ],
        ),
    ]
