# Generated by Django 5.2 on 2025-05-06 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0008_sahsiyardim_sahsiyardimci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosyatutari',
            name='dosya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yardim_tutarlari', to='dosyalar.dosya'),
        ),
        migrations.AlterField(
            model_name='maddiyardim',
            name='dosyalar',
            field=models.ManyToManyField(blank=True, related_name='maddi_yardimlar', to='dosyalar.dosya'),
        ),
    ]
