# Generated by Django 5.2 on 2025-05-05 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0009_manuelaile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dosyatutari',
            unique_together={('maddi_yardim', 'dosya')},
        ),
        migrations.AddField(
            model_name='dosyatutari',
            name='manuel_aile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yardim_tutarlari', to='dosyalar.manuelaile'),
        ),
        migrations.AddField(
            model_name='maddiyardim',
            name='manuel_aileler',
            field=models.ManyToManyField(blank=True, related_name='maddi_yardimlar', to='dosyalar.manuelaile'),
        ),
        migrations.AlterField(
            model_name='dosyatutari',
            name='dosya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yardim_tutarlari', to='dosyalar.dosya'),
        ),
        migrations.AlterField(
            model_name='maddiyardim',
            name='dosyalar',
            field=models.ManyToManyField(blank=True, related_name='maddi_yardimlar', to='dosyalar.dosya'),
        ),
        migrations.AlterUniqueTogether(
            name='dosyatutari',
            unique_together={('maddi_yardim', 'dosya'), ('maddi_yardim', 'manuel_aile')},
        ),
    ]
