# Generated by Django 5.2 on 2025-05-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0010_alter_dosyatutari_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maddiyardim',
            name='manuel_aileler',
        ),
        migrations.AlterUniqueTogether(
            name='dosyatutari',
            unique_together={('maddi_yardim', 'dosya')},
        ),
        migrations.RemoveField(
            model_name='dosyatutari',
            name='manuel_aile',
        ),
        migrations.DeleteModel(
            name='ManuelAile',
        ),
    ]
