# Generated by Django 5.2 on 2025-05-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0011_remove_maddiyardim_manuel_aileler_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuelMaddiYardim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('adres', models.TextField()),
                ('tutar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Manuel Maddi Yardım',
                'verbose_name_plural': 'Manuel Maddi Yardımlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
