# Generated by Django 5.2 on 2025-05-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0009_alter_dosyatutari_dosya_alter_maddiyardim_dosyalar'),
        ('dosyalar', '0012_manuelmaddiyardim'),
    ]

    operations = [
    ]
