# Generated by Django 5.2 on 2025-05-06 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0013_merge_20250506_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AileBilgisi',
        ),
    ]
