# Generated by Django 5.2 on 2025-05-06 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0014_remove_aile_bilgileri'),
    ]

    operations = [
        migrations.CreateModel(
            name='AileBilgisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('kimlik_no', models.CharField(blank=True, max_length=20, null=True)),
                ('yakinlik', models.CharField(choices=[('KENDISI', 'Kendisi'), ('ES', 'Eş'), ('COCUK', 'Çocuk'), ('ANNE', 'Anne'), ('BABA', 'Baba'), ('KARDES', 'Kardeş'), ('DIGER', 'Diğer')], default='DIGER', max_length=20)),
                ('cinsiyet', models.CharField(choices=[('E', 'Erkek'), ('K', 'Kadın')], default='E', max_length=1)),
                ('dogum_tarihi', models.DateField(blank=True, null=True)),
                ('engel_durumu', models.BooleanField(blank=True, null=True)),
                ('engel_aciklama', models.TextField(blank=True, null=True)),
                ('dosya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aile_bilgileri', to='dosyalar.dosya')),
            ],
            options={
                'db_table': 'aile_bilgileri',
            },
        ),
    ]
