# Generated by Django 5.2 on 2025-05-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0016_manuelmaddiyardimkayit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maddiyardim',
            options={'ordering': ['-created_at'], 'verbose_name': 'Maddi Yardım', 'verbose_name_plural': 'Maddi Yardımlar'},
        ),
        migrations.RemoveField(
            model_name='maddiyardim',
            name='dosyalar',
        ),
        migrations.AddField(
            model_name='maddiyardim',
            name='yardim_tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Yardım Tutarı'),
        ),
        migrations.AlterField(
            model_name='maddiyardim',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='maddiyardim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi'),
        ),
        migrations.AlterField(
            model_name='maddiyardim',
            name='tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Tutar'),
        ),
        migrations.AlterField(
            model_name='maddiyardim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AlterField(
            model_name='maddiyardim',
            name='yardim_yapan_ad_soyad',
            field=models.CharField(default='', max_length=100, verbose_name='Yardım Yapan Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='maddiyardim',
            name='yardim_yapan_telefon',
            field=models.CharField(default='', max_length=20, verbose_name='Yardım Yapan Telefon'),
        ),
    ]
