# Generated by Django 5.2 on 2025-05-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0017_alter_maddiyardim_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maddiyardim',
            name='tutar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Verilen Tutar'),
        ),
    ]
