# Generated by Django 5.2 on 2025-05-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0019_alter_maddiyardim_tutar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dosya',
            options={'default_related_name': 'dosyalar', 'ordering': ['dosya_no']},
        ),
        migrations.AlterField(
            model_name='ailebilgisi',
            name='cinsiyet',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='ailebilgisi',
            name='yakinlik',
            field=models.CharField(max_length=20),
        ),
    ]
