# Generated by Django 5.2 on 2025-05-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0020_alter_dosya_options_alter_ailebilgisi_cinsiyet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosya',
            name='engel_durumu',
            field=models.BooleanField(default=False, verbose_name='Engel Durumu'),
        ),
    ]
