# Generated by Django 5.2 on 2025-05-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0021_dosya_engel_durumu'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='belge',
            unique_together=set(),
        ),
    ]
