# Generated by Django 5.2 on 2025-05-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dosyalar', '0022_alter_belge_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='belge',
            unique_together={('dosya', 'belge_turu')},
        ),
    ]
